import pg from "../../databases/postgres";

export default async function createTableFavoritos() {
    // Create the "Favoritos" table if it doesn't exist
    await pg.query(`
            CREATE TABLE IF NOT EXISTS "Favoritos" (
                "idFavorito" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                "idProduto" integer NOT NULL,
                "idUsuario" integer NOT NULL,
                "isFavorito" bool DEFAULT true
            );
        `);

    // VERIFICA SE JÁ EXISTE A RELAÇÃO
    const userConstraintCheck = await pg.query(`
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'Favoritos' 
            AND constraint_name = 'fk_favorito_user';
        `);

    if (userConstraintCheck.rows.length === 0) {
        await pg.query(`
                ALTER TABLE "Favoritos" 
                ADD CONSTRAINT "fk_favorito_user" 
                FOREIGN KEY ("idUsuario") 
                REFERENCES "User" ("idUsuario");
            `);
    }

    // VERIFICA SE JÁ EXISTE A RELAÇÃO
    const alimentoConstraintCheck = await pg.query(`
            SELECT constraint_name 
            FROM information_schema.table_constraints 
            WHERE table_name = 'Favoritos' 
            AND constraint_name = 'fk_favorito_alimento';
        `);

    if (alimentoConstraintCheck.rows.length === 0) {
        await pg.query(`
                ALTER TABLE "Favoritos" 
                ADD CONSTRAINT "fk_favorito_alimento" 
                FOREIGN KEY ("idProduto") 
                REFERENCES "Alimentos" ("idProduto");
            `);
    }
}
